# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

OKTA_CLIENT_ID: "0oa3v80mi4vgQKV7c5d7"

OKTA_CLIENT_SECRET: "hbtUeMFoQ8c8DvsVnzrZ6yUrs3KF_wL54Bpp45V_"

OKTA_ORG: "Wizeline"
OKTA_DOMAIN: "dev-39747048.okta.com"

OKTA_URL: "http://dev-39747048.okta.com"

OKTA_ISSUER: "https://dev-39747048.okta.com/oauth2/default"

OKTA_AUTH_SERVER_ID: "default"

OKTA_REDIRECT_URI: "http://localhost:3000/users/auth/oktaoauth/callback"
