<OmniAuth::AuthHash
  credentials=#
    <
      OmniAuth::AuthHash
      expires=true
      expires_at=1644858256
      token="eyJraWQiOiJ3aW1NNVdhRHVlWVdFcXdFOVFOWXJMQjhoTDJGSUZsNWk2NEJDbE44a0g0IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmJobUl5TF9CaUVwSkpfTVRUU3dfeHdUeWZpNEpZRExqamFUR1hVMENFRzAiLCJpc3MiOiJodHRwczovL2Rldi0zOTc0NzA0OC5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NDQ4NTQ2NTYsImV4cCI6MTY0NDg1ODI1NiwiY2lkIjoiMG9hM3Y4MG1pNHZnUUtWN2M1ZDciLCJ1aWQiOiIwMHUzdjFiZTBpd254Z2tlUzVkNyIsInNjcCI6WyJwcm9maWxlIiwib3BlbmlkIiwiZW1haWwiXSwic3ViIjoidmljdG9yLmluZmFudGVAd2l6ZWxpbmUuY29tIn0.i0BhmR8iPMd84_7E52AU-MQy9wBp8vjbeyp3Fgsk2wsHc-E-LyWWmmstX50FOaroCQP48-eNJlK4gJqVuXffjLAcm-DCvB-16wb4pnLEYSIWteZLvTFyJLqz9dxUX2oftM9DsXo4sSpaRaOyKcTCzZ2pEdiwOsHUGh3snOHmvovn7GMDKE8D8dpxBh66jFWi66M6cQBM2EIfdV0qUUQs4_2T9h6ejAZ0W1yGLYxySStVIZJB3_fCKU5QlmRBAYU--jlRHvZsrcpsy4Wf3P4TRGvpVfP2XBAHnqp-t3XkFUKjtyYhHIFWG3TSP2ge_OecVbS_LxYm1TeIkDV_W-gsVg">
      extra=#
        <
          OmniAuth::AuthHash
          id_info=#
            <
              OmniAuth::AuthHash
              aud="api://default"
              cid="0oa3v80mi4vgQKV7c5d7"
              exp=1644858256
              iat=1644854656
              iss="https://dev-39747048.okta.com/oauth2/default"
              jti="AT.bhmIyL_BiEpJJ_MTTSw_xwTyfi4JYDLjjaTGXU0CEG0"
              scp=#
                <
                  Hashie::Array
                  ["profile",
                  "openid",
                  "email"]
                >
              sub="victor.infante@wizeline.com"
              uid="00u3v1be0iwnxgkeS5d7"
              ver=1
            >
            id_token="eyJraWQiOiJ3aW1NNVdhRHVlWVdFcXdFOVFOWXJMQjhoTDJGSUZsNWk2NEJDbE44a0g0IiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmJobUl5TF9CaUVwSkpfTVRUU3dfeHdUeWZpNEpZRExqamFUR1hVMENFRzAiLCJpc3MiOiJodHRwczovL2Rldi0zOTc0NzA0OC5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NDQ4NTQ2NTYsImV4cCI6MTY0NDg1ODI1NiwiY2lkIjoiMG9hM3Y4MG1pNHZnUUtWN2M1ZDciLCJ1aWQiOiIwMHUzdjFiZTBpd254Z2tlUzVkNyIsInNjcCI6WyJwcm9maWxlIiwib3BlbmlkIiwiZW1haWwiXSwic3ViIjoidmljdG9yLmluZmFudGVAd2l6ZWxpbmUuY29tIn0.i0BhmR8iPMd84_7E52AU-MQy9wBp8vjbeyp3Fgsk2wsHc-E-LyWWmmstX50FOaroCQP48-eNJlK4gJqVuXffjLAcm-DCvB-16wb4pnLEYSIWteZLvTFyJLqz9dxUX2oftM9DsXo4sSpaRaOyKcTCzZ2pEdiwOsHUGh3snOHmvovn7GMDKE8D8dpxBh66jFWi66M6cQBM2EIfdV0qUUQs4_2T9h6ejAZ0W1yGLYxySStVIZJB3_fCKU5QlmRBAYU--jlRHvZsrcpsy4Wf3P4TRGvpVfP2XBAHnqp-t3XkFUKjtyYhHIFWG3TSP2ge_OecVbS_LxYm1TeIkDV_W-gsVg"
            raw_info=#
              <
                OmniAuth::AuthHash
                email="victor.infante@wizeline.com"
                email_verified=true
                family_name="Infante
                Mendez"
                given_name="Victor"
                locale="en_US"
                name="Victor
                Infante
                Mendez"
                preferred_username="victor.infante@wizeline.com"
                sub="00u3v1be0iwnxgkeS5d7"
                updated_at=1644636878
                zoneinfo="America/Los_Angeles"
              >
        >
          info=#
            <
              OmniAuth::AuthHash::InfoHash
              email="victor.infante@wizeline.com"
              first_name="Victor"
              image=nil
              last_name="Infante
              Mendez"
              name="Victor
              Infante
              Mendez"
            >
  provider="oktaoauth"
  uid="00u3v1be0iwnxgkeS5d7"
>

